[package]
name = "seqalign"
version = "0.1.0"
authors = ["yamule <1697130+yamule@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
